name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: maddox/actions/ssh@master
    - run: cd /home/falghifa/judge.falghifari.com/ && git pull
    - env: |
        PRIVATE_KEY
        HOST
        USER
        PORT
