name: Deploy to server

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: maddox/actions/ssh@master
      with:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        PORT: ${{ secrets.PORT }}
    - run: cd /home/falghifa/judge.falghifari.com/ && git pull
